import Head from "next/head";
import { useState } from "react";
import axios from "axios";
import { GetServerSideProps, NextPage } from "next";

interface ShareData {
  title: string;
  text: string;
}

const Home: NextPage<ShareData> = (props) => {
  const [title, setTitle] = useState(props.title);
  const [text, setText] = useState(props.text);

  const shareHandler = async () => {
    const result: ShareData = await (
      await axios.post(`http://localhost:3000/api`, { title, text })
    ).data;
    if (result) {
      alert("データ更新成功");
      return;
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-red-500">main</h1>
        <input
          type="text"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
        />
        <textarea
          defaultValue={text}
          onChange={(e) => setText(e.target.value)}
        ></textarea>
        <button onClick={shareHandler}>share</button>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<ShareData> = async () => {
  console.log("ssr");

  const result: ShareData = await (
    await axios.get(`http://localhost:3000/api`)
  ).data;

  return {
    props: result,
  };
};

export default Home;
